### ISSUE TITLE
Execute Collection methods

### ISSUE THREAD

**Issue by heubachmedia** [4d/4D-Plugin-SDK#14]
Currently it is not possible to execute Collection (PA_CollectionRef) methods like:

coll._push()_

**Comment by guillaume-kotulski** [comment]
The command *push* can be emulated by PA_SetCollectionElement. Which specific command would you like to add ? 

Edit:
We have registered your feature request to get a more generic way to call all the methods of a Collection.

**Comment by heubachmedia** [comment]
>  Which specific command would you like to add ?

Generic, all commands: orderBy(), indices(), query …

Same with ORDA.

**Comment by heubachmedia** [comment]
We also need a PA_DuplicateCollection (like PA_DuplicateObject). Because i cannot call collection-methods i **cannot** deep-copy a collection!

**Comment by guillaume-kotulski** [comment]
The feature will arrive in the future version of 4D.

**Comment by heubachmedia** [comment]
v18 or 17R6?

**Comment by guillaume-kotulski** [comment]
Normally 17R6
