### ISSUE TITLE
PA_Get4DVersion returns no version in preemptive threads

### ISSUE THREAD

**Issue by heubachmedia** [4d/4D-Plugin-SDK#6]
calling PA_Get4DVersion in a preemptive thread, PA_Get4DVersion & 0x0000FFFF returns always 0. In cooperative thread it's ok.

**Comment by miyako** [comment]
the entry point is explicitly marked as ``false`` (not thread safe) 

https://github.com/4d/4D-Plugin-SDK/blob/master/4D%20Plugin%20API/EntryPoints.h

**Comment by miyako** [comment]
for BLOB, there is a workaround, which is to use PA_GetBlobHandleParameter
ACI0098388, fixed sometime during v17 beta.

but PA_GetBlobParameter is not compatible, and there are no workarounds for picture or arrays.

**Comment by heubachmedia** [comment]
I know, quite everything is marked as **not** thread safe. This is a reminder of which entry points i need. The `false` of thread safety flag is more a "not yet tested for thread safety".
Why is EX_CREATE_RECORD not thread safe??? Strange

**Comment by guillaume-kotulski** [comment]
https://github.com/4d/4D-Plugin-SDK/issues/7
