### ISSUE TITLE
What version of 4D does this API support?

### ISSUE THREAD

**Issue by spiffyguy** [4d/4D-Plugin-SDK#9]
I assume there is a level of "It's up to you" mentality but I imagine there is a supported version for the API as well as a supported version for the Wizard itself.

Ie:  4D Plugin API - v14 to v17, 4D Plugin Wizard - v15 to v17

Anyone know the specific answer?

Thanks in advanced,
- Matt

**Comment by guillaume-kotulski** [comment]
Hello,

For the API:
* The tag "17.0" https://github.com/4d/4D-Plugin-SDK/tree/v17.0 added the possibility to manage collection and objects.
* The tag "17.0.1" added the thread safety for some commands for the build 227009 and later.

The Wizard is compatible with v17 and before.
